### ISSUE TITLE
NameError: name 'filter_out_kernel_core_files' is not defined

### ISSUE THREAD

**Issue by tpgxyz** [systemd/mkosi-initrd#13]
Hi,

i'm playing a bit with mkosi-initrd on my OpenMandriva aarch64 gear and i get this:

```
$KERNEL_VERSION not defined, using 6.0.0-server-0.rc5.3omv4090
Installing modules for kernel 6.0.0-server-0.rc5.3omv4090
Cannot query file list of kernel-core-6.0.0-server-0.rc5.3omv4090: Command '['rpm', '-ql', 'kernel-core-6.0.0-server-0.rc5.3omv4090']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/lib/mkosi-initrd/mkosi.finalize", line 300, in <module>
    do_initrd(root)
  File "/usr/lib/mkosi-initrd/mkosi.finalize", line 275, in do_initrd
    copy_in_modules(root)
  File "/usr/lib/mkosi-initrd/mkosi.finalize", line 130, in copy_in_modules
    copy_in_modules_kver(root, kver)
  File "/usr/lib/mkosi-initrd/mkosi.finalize", line 106, in copy_in_modules_kver
    good = copy_in_modules_from_fs(root, kver)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/mkosi-initrd/mkosi.finalize", line 79, in copy_in_modules_from_fs
    filter_out_kernel_core_files)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'filter_out_kernel_core_files' is not defined
‣  (Unmounting image)
```

**Comment by behrmann** [comment]
Looks like from what's needed `kernel_core_skip_file` could make sense, you could give that a try.
